name: CI

on:
  push:
    branches:
      - '**'
    tags:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      - name: Install dependencies
        run: npm install

      - name: Run linter
        run: make lint

      - name: SonarCloud Scan
        uses: sonarsource/sonarqube-scan-action@v6
        with:
          args: >
            -Dsonar.projectKey=g3nnadevich_frontend-project-46
            -Dsonar.organization=g3nnadevich
            -Dsonar.host.url=https://sonarcloud.io
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}